version: "3.8"
services:
  # NGINX Server
  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
    command: ["sh", "-c", "ln -snf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo Asia/Jakarta > /etc/timezone && nginx -g 'daemon off;'"]
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
  # PHP-FPM
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    image: php-fpm:7.4.33
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
  # MariaDB
  mariadb:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION}
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}